### ISSUE TITLE
Include python bindings in recipe

### ISSUE THREAD

**Issue by razvanch** [conda-forge/zstd-feedstock#45]
Hi,

Would it be possible to add the python zstd bindings (https://pypi.org/project/zstd/) to this recipe? Right now I have to install them separately via pip, and that causes problems, as the names of the packages clash.

Thanks,
Razvan

**Comment by jakirkham** [comment]
Maybe you are looking for [`zstandard`]( https://github.com/conda-forge/zstandard-feedstock )? This just contains the C library.

**Comment by razvanch** [comment]
Hmm ok, I'll see if I can use those bindings instead. Thanks.
