### ISSUE TITLE
zstd version is out of date

### ISSUE THREAD

**Issue by ahrib** [conda-forge/zstd-feedstock#70]
### Comment:

Hi the included zstd version (1.5.2) was released on Jan 2022 and is more than a year older than the current stable version (1.5.5) released Apr 5 2023.

Is there a plan to update?

**Comment by jakirkham** [comment]
There's a bot PR to update ( https://github.com/conda-forge/zstd-feedstock/pull/69 ), but it appears to fail on CI

If this is of interest, would suggest starting by looking at what the failure is
